### ISSUE TITLE
npm install @cloudnative/health 

### ISSUE THREAD

**Issue by ponessa** [CloudNativeJS/cloud-health-connect#6] opened 2019-04-09 00:29 UTC
Trying to install as per this README.md:
```
npm install @cloudnative/health-connect
```
Fails:
```
npm ERR! code E404
npm ERR! 404 Not Found: @cloudnative/health-connect@latest
```
From log:
```
2 info using npm@6.4.0
3 info using node@v9.5.0
4 verbose npm-session 17d68231a32e5b9a
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@cloudnative%2fhealth-connect 431ms
8 silly fetchPackageMetaData error for @cloudnative/health-connect@latest 404 Not Found: @cloudnative/health-connect@latest
```

**Comment by steven-ponessa** [comment] 2019-04-09 01:41
Note that https://registry.npmjs.org/@cloudnative%2fhealth-connect is found and is accessible. 

![image](https://user-images.githubusercontent.com/40922527/55767437-f704ac80-5a46-11e9-93d7-8fc18bd58d3b.png)

**Comment by BethGriggs** [comment] 2019-04-09 09:32
Hi @ponessa  - I have just tried `npm install @cloudnative/health-connect` using Node `v9.5.0` and npm `6.4.0` and it successfully installed. I wonder if this was an intermittent registry issue? Could you tell me which OS/platform you're on?

**Comment by ponessa** [comment] 2019-04-09 13:04
Hi Bethany,
 
I am using MacOS High Sierra (v10.13.6).  I have tried with multiple version of node but get the same results regardless.  I have tried it with my VPN both on and off as well (thinking that it may be a firewall issue).
 

 
I have attached the log as well, although I don't think it provides any additional insight.
 
I appreciate any help or insight you may be able to provide.
 
Thanks, SteveGBS Role-Based Dashboard, Business Analysts, Executive IT ArchitectContact Information:Tie Line: 8-938-7234Outside Line: 720-396-7234Internet: ponessa@us.ibm.com
 
 
----- Original message -----From: Bethany Nicolle Griggs <notifications@github.com>To: CloudNativeJS/cloud-health-connect <cloud-health-connect@noreply.github.com>Cc: "Steven J. Ponessa" <ponessa@us.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [CloudNativeJS/cloud-health-connect] npm install @cloudnative/health (#6)Date: Tue, Apr 9, 2019 5:32 AM 
Hi @ponessa - I have just tried npm install @cloudnative/health-connect using Node v9.5.0 and npm 6.4.0 and it successfully installed. I wonder if this was an intermittent registry issue? Could you tell which OS/platform you're on?

**Comment by BethGriggs** [comment] 2019-06-04 12:48
Closing as it has been confirmed that the issue is not specific to this module as it happens with all scoped modules

**Closed as completed by BethGriggs** 2019-06-04 12:48 UTC
